export enum RecallType {
  IMAGE = 'IMAGE',
  TEXT = 'TEXT',
  AUDIO = 'AUDIO',
  VIDEO = 'VIDEO',
  DOCUMENT = 'DOCUMENT',
  HYBRID = 'HYBRID'
}

export interface SemanticDiff {
  id: string;
  timestamp: number;
  description: string; // "Changed style to cyberpunk"
  previewImage?: string; // Snapshot of this state (for visual reference)
  content?: string; // The full content snapshot for restoration
  author: 'user' | 'system' | 'gemini';
}

export interface FinancialData {
  amount?: number;
  currency?: string;
  date?: string; // ISO Date YYYY-MM-DD
  category?: string; // e.g., "Utility", "Tax", "Groceries"
  entity?: string; // Vendor, Sender, or Bank Name
  lineItems?: string[]; // Brief summary of what was bought
}

export interface RecallMetadata {
  location?: string;
  weather?: string;
  mood?: string;
  tags: string[];
  sourceApp?: string; // e.g., "Chrome", "Camera"
  fileSize?: string;
  financial?: FinancialData; // New structured data field
}

export interface RecallFile {
  id: string;
  title: string;
  description: string; // Generated by Gemini
  type: RecallType;
  content: string; // Base64 data or text content
  thumbnail: string; // For docs/audio, this might be an icon or generated placeholder
  createdAt: number;
  updatedAt: number;
  metadata: RecallMetadata;
  history: SemanticDiff[]; // Infinite undo stack
  vectorId?: string; // For Qdrant/Vector search simulation
  
  // Spatial Coordinates for Canvas Mode
  x?: number;
  y?: number;
}

export interface ChatMessage {
  role: 'user' | 'model';
  text: string;
  timestamp: number;
}